config/routes.rb
YouGiveGoods::Application.routes.draw do
  
  devise_for :users
  
  root :to => "home#index"
  
  devise_for :admins
  
  resources :home
  
  resources :drives
  
  resources :campaigns
  
  namespace :admin do
    resources :dashboards
  end
  
  resources :products
  
  resources :users
  
  resources :dashboards
  

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  
  has_attached_file :image
  validates_attachment_content_type :image,:styles => { :medium => "300x300>", :thumb => "100x100>" }, :content_type => ["image/jpg", "image/jpeg", "image/png", "video/mp4"]
  
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: ["edit", "update", "destroy"]
   before_filter :is_admin?
  
  def index
    @campaigns = Campaign.all
  end
  
  def new
    @campaign = Campaign.new
  end
  
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.status = "Registered"
    if @campaign.save
      redirect_to campaigns_path
      flash[:notice] = "Campaign was successfully created."
    else
      render :action => "new"
    end
  end
  
  def edit
  end
  
  def update
    if @campaign.update_attributes(campaign_params)
      redirect_to campaigns_path
      flash[:notice] = "Campaign was successfully updated."
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @campaign.destroy
    redirect_to campaigns_path
    flash[:notice]= "Campaign was successfully deleted."
  end
  
  private
  def campaign_params
    params.require(:campaign).permit(:campaign_type, :status,:name,:organization,:npo_name,:campaign_url,:description,:start_date,:end_date,:goal,:goal_unit_id,:updated_by,:logo,:image)
  end
  
  def set_campaign
    @campaign = Campaign.find(params[:id])
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for @campaign do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %>prohibited this campaign from being saved.</h2>
      <ul>
        <% @campaign.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr><td colspan="5"><h4>Enter the basic details of your campaign</h4></td></tr>

    <tr><td>&nbsp;</td></tr>

    <tr><td>Organization</td>
      <td><%= f.text_field :organization %></td></tr>

    <tr>
      <td>Campaign Name</td>
      <td><%= f.text_field :name %></td>
    </tr>

    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>Non-Profit Organization</td>
      <td><%= f.text_field :npo_name %></td>
    </tr>

    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>Campaign Type</td>
      <td><%= f.select :campaign_type, options_for_select([["contest"],["supercontest,"],["subcontest"],["campaign"],["super campaign"],["subcampaign"]]) %></td>
    </tr>

    <tr><td>&nbsp;</td></tr>


    <tr>
      <td>Campaign Description</td>
      <td><%= f.text_area :description %></td>
    </tr>

    <tr><td>&nbsp;</td></tr>

    <tr>
      <td>Campaign GoalUnits</td>
      <td><span style="margin-right: 10px;">$</span><%= f.text_field :goal %></td>
    </tr>

    <tr><td>&nbsp;</td></tr>

    <tr><td>Campaign Logo</td>
      <td><%= f.file_field :logo %></td>
    </tr>

    <tr><td>&nbsp;</td></tr>

    <tr><td>Campaign Photo</td>
      <td><%= f.file_field :image %></td>
    </tr>

    <tr><td>&nbsp;</td></tr>

    <tr><td><h4>Pick the start and end dates for your drive</h4></td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>Start Date</td>
      <td><div id="datetimepicker1" class="input-append date">
          <style>
            .btn{
              padding :0;
            }
          </style>
          <%= f.text_field :start_date, "data-format"=>"dd/MM/yyyy hh:mm:ss" %>
          <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
          </span>
        </div> </td>
    </tr>

    <tr>
      <td>End Date</td>
      <td><div id="datetimepicker2" class="input-append date">
          <style>
            .btn{
              padding :0;
            }
          </style>
          <%= f.text_field :end_date, "data-format"=>"dd/MM/yyyy hh:mm:ss" %>
          <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar">
            </i>
          </span>
        </div></td>
    </tr>

    <tr><td>&nbsp;</td></tr>

    <tr><td>Campaign url</td>
      <td><%= f.text_field :campaign_url %></td></tr>

    <tr><td>&nbsp;</td></tr>

    <tr><td><%= f.submit :save, :class=> "btn btn-success" ,:style => "width:300px;height:50px;" %></td></tr>
  </table>

<% end %>

<script>
  $(function() {
    $('#datetimepicker1').datetimepicker({
      language: 'en'
    });
  });

  $(function() {
    $('#datetimepicker2').datetimepicker({
      language: 'en'
    });
  });
</script>

app/views/campaigns/edit.html.erb
<%= render "form" %>

app/views/campaigns/index.html.erb
<table class="table table-bordered table-striped">
  <tr>
    <td colspan="12"><span style="float:right;"><%= link_to "Add New",new_campaign_path, :class => "btn btn-small btn-info"%></span></td>
  </tr>
  <tr>
    <th>Campaign Type</th>
    <th>Status</th>
    <th>Name</th>
    <th>Organization</th>
    <th>NPO Name</th>
    <th>Campaign url</th>
    <th>Description</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Goal</th>
    <th>Action</th>
  </tr>
  
  <% @campaigns.each do |camp| %>
  <tr>
    <td><%= camp.campaign_type %></td>
    <td><%= camp.status %></td>
    <td><%= camp.name %></td>
    <td><%= camp.organization %></td>
    <td><%= camp.npo_name %></td>
    <td><%= camp.campaign_url %></td>
    <td><%= camp.description %></td>
    <td><%= camp.start_date %></td>
    <td><%= camp.end_date %></td>
    <td>$<%= camp.goal %></td>
    <td><%= link_to "Edit", edit_campaign_path(camp), :class => "btn btn-mini btn-info" %>|
        <%= link_to "Delete", camp, :data => {:confirm => "Are You Sure?"},:method => :delete, :class => "btn btn-mini btn-danger" %></td>
  </tr>
  <% end %>
</table>

app/views/campaigns/new.html.erb
<%= render "form" %>