config/routes.rb
YouGiveGoods::Application.routes.draw do
  
  devise_for :users
  
  root :to => "home#index"
  
  devise_for :admins
  
  resources :home
  
  resources :drives
  
  resources :campaigns
  
  namespace :admin do
    resources :dashboards
  end
  
  resources :products
  
  resources :users
  
  resources :dashboards
  

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_products ,only: ["edit", "update", "destroy"]
   before_filter :is_admin?
   
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to products_path
      flash[:notice]= "Product was successfully created."
    else
      render :action => "new"
    end
  end
  
  def edit
    
  end
  
  def update
    if @product.update_attributes(product_params)
      redirect_to products_path
      flash[:notice]= "Product was successfully updated."
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @product.destroy
    redirect_to products_path
    flash[:notice] = "Product was successfully deleted."
  end
  
  private
  
  def set_products
    @product = Product.find(params[:id])
  end
  
  def product_params
    params.require(:product).permit(:product_type,:status,:name,:description,:base_unit,:product_attributes,:image_url,:categories,:cost,:pounds,:updated_by)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<% if @product.errors.any? %>
<div id ="error_explanation">
  <h2><%= pluralize(@product.errors.count, "error") %>prohibited this product from being saved.</h2>
  <ul>
    <%= @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :product_type, "Type" %>
  <%= f.text_field :product_type %>
</div>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name  %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="field">
  <%= f.label :base_unit,"Base Unit" %>
  <%= f.text_field :base_unit %>
</div>

<div class="field">
  <%= f.label :status %>
  <%= f.text_field :status %>
</div>

<div class="field">
  <%= f.label :product_attributes, "Attributes" %>
  <%= f.text_field :product_attributes %>
</div>

<div class="field">
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
</div>

<div class="field">
  <%= f.label :categories %>
  <%= f.text_field :categories %>
</div>

<div class="field">
  <%= f.label :cost %>
  <%= f.text_field :cost %>
</div>

<div class="field">
  <%= f.label :pounds %>
  <%= f.text_field :pounds %>
</div>

<div class="action">
  <%= f.submit :save %>
</div>
<% end %>

app/views/products/edit.html.erb
<%= render "form" %>

app/views/products/index.html.erb
<table class="table table-bordered table-condensed">
  <tr>
    <td colspan="12">
      <span style="float:right;"><%= link_to "Add New", new_product_path, :class=> "btn btn-small btn-info" %></span>
    </td>
  </tr>
  
  <tr>
    <th>Type</th>
    <th>Status</th>
    <th>Name</th>
    <th>Description</th>
    <th>Base Unit</th>
    <th>Attributes</th>
    <th>Image url</th>
    <th>Categories</th>
    <th>Cost</th>
    <th>Pounds</th>
    <th>Action</th>
  </tr>
  
  <% @products.each do |product| %>
  <tr>
    <td><%= product.product_type %></td>
    <td><%= product.status %></td>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.base_unit %></td>
    <td><%= product.product_attributes %></td>
    <td><%= product.image_url %></td>
    <td><%= product.categories %></td>
    <td>$<%= product.cost %></td>
    <td>$<%= product.pounds %></td>
    <td><%= link_to "Edit",edit_product_path(product), :class => "btn btn-mini btn-info" %>|
    <%= link_to "Delete",product, :data => {:confirm => "Are you sure?"}, :method => "delete", :class=>"btn btn-mini btn-danger" %></td>
  </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<%= render "form" %>