config/routes.rb
YouGiveGoods::Application.routes.draw do
  
  devise_for :users
  
  root :to => "home#index"
  
  devise_for :admins
  
  resources :home
  
  resources :drives
  
  resources :campaigns
  
  namespace :admin do
    resources :dashboards
  end
  
  resources :products
  
  resources :users
  
  resources :dashboards
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  
  has_attached_file :image
  validates_attachment_content_type :image,:styles => { :medium => "300x300>", :thumb => "100x100>" }, :content_type => ["image/jpg", "image/jpeg", "image/png", "video/mp4"]
  
end

app/models/drive.rb
class Drive < ActiveRecord::Base
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  
  has_attached_file :image
  validates_attachment_content_type :image,:styles => { :medium => "300x300>", :thumb => "100x100>" }, :content_type => ["image/jpg", "image/jpeg", "image/png", "video/mp4"]
  
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  
  validates :first_name, :last_name, :presence => true
  
  has_many :authentications
       
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    authentication = Authentication.where(:provider => auth.provider, :uid => auth.uid).first
    user = User.find_by_email(auth.info.email)
    if user
      if authentication.present?
        authentication.update_attributes(:provider=>auth.provider,:uid=> auth.uid,  :user_id => user.id)
      else
        authentication= Authentication.create(:provider=>auth.provider,:uid=> auth.uid, :user_id => user.id)
      end
    end
    unless authentication
      user = User.new(first_name:auth.extra.raw_info.first_name,
        last_name:auth.extra.raw_info.last_name,
        email:auth.info.email,
        password:Devise.friendly_token[0,20],
        confirmation_token: nil,
        confirmed_at:Time.now
      )
      unless user.save
        return nil
      else
        authentication= Authentication.create(:provider=>auth.provider,:uid=> auth.uid, :user_id => user.id)
      end
    end
    authentication.save
    authentication.user
  end
  
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    authentication = Authentication.where(:provider => access_token.provider, :uid => access_token.uid).first
    data = access_token.info
    user = User.find_by_email(data["email"])
    if user
      if authentication.present?
        authentication.update_attributes(:provider=>access_token.provider,:uid=> access_token.uid,  :user_id => user.id)
      else
        authentication= Authentication.create(:provider=>access_token.provider,:uid=> access_token.uid, :user_id => user.id)
      end
    end
    unless authentication
      user = User.new(first_name:data["first_name"],
        last_name:data["last_name"],
        email:data["email"],
        password:Devise.friendly_token[0,20],
        confirmation_token: nil,
        confirmed_at:Time.now
      )
      unless user.save
        return nil
      else
        authentication= Authentication.create(:provider=>access_token.provider,:uid=> access_token.uid,  :user_id => user.id)
      end
    end
    authentication.save
    authentication.user
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: ["edit", "update", "destroy"]
   before_filter :is_admin?
  
  def index
    @campaigns = Campaign.all
  end
  
  def new
    @campaign = Campaign.new
  end
  
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.status = "Registered"
    if @campaign.save
      redirect_to campaigns_path
      flash[:notice] = "Campaign was successfully created."
    else
      render :action => "new"
    end
  end
  
  def edit
  end
  
  def update
    if @campaign.update_attributes(campaign_params)
      redirect_to campaigns_path
      flash[:notice] = "Campaign was successfully updated."
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @campaign.destroy
    redirect_to campaigns_path
    flash[:notice]= "Campaign was successfully deleted."
  end
  
  private
  def campaign_params
    params.require(:campaign).permit(:campaign_type, :status,:name,:organization,:npo_name,:campaign_url,:description,:start_date,:end_date,:goal,:goal_unit_id,:updated_by,:logo,:image)
  end
  
  def set_campaign
    @campaign = Campaign.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @drives = Drive.all
    @campaigns = Campaign.all
  end
  
end

app/controllers/drives_controller.rb
class DrivesController < ApplicationController
  before_action :set_drive ,only: ["edit", "update", "destroy", "show"]
  before_filter :is_admin?
  
  def index
    @drives = Drive.all
  end
  
  def new
    @drive = Drive.new
  end
  
  def show
    
  end
  
  def create
    @drive = Drive.new(drive_params)
    @drive.status = "Registered"
    if @drive.save
      redirect_to @drive
      flash[:notice]= "Your Drive Has Been Created."
    else
      render :action => "new"
    end
  end
  
  def edit
  end
  
  def update
    if @drive.update_attributes(drive_params)
      redirect_to drives_path
      flash[:notice]= "Your Drive Has Been Updated."
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @drive.destroy
    redirect_to drives_path
    flash[:notice]= "Drive was successfully deleted."
  end
  
  private
  
  def drive_params
    params.require(:drive).permit(:drive_type,:status,:name,:organization,:npo_name,:drive_url,:description,:goods_type,:start_date,:end_date,:goal,:goal_unit_id,:updated_by,:logo,:on_behalfof,:image)
  end
  
  def set_drive
    @drive = Drive.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_products ,only: ["edit", "update", "destroy"]
   before_filter :is_admin?
   
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to products_path
      flash[:notice]= "Product was successfully created."
    else
      render :action => "new"
    end
  end
  
  def edit
    
  end
  
  def update
    if @product.update_attributes(product_params)
      redirect_to products_path
      flash[:notice]= "Product was successfully updated."
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @product.destroy
    redirect_to products_path
    flash[:notice] = "Product was successfully deleted."
  end
  
  private
  
  def set_products
    @product = Product.find(params[:id])
  end
  
  def product_params
    params.require(:product).permit(:product_type,:status,:name,:description,:base_unit,:product_attributes,:image_url,:categories,:cost,:pounds,:updated_by)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :is_admin?
   
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/drives_helper.rb
module DrivesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amp Your Good</title>
    <%= stylesheet_link_tag    "admin","bootstrap.css", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "bootstrap.min.css","bootstrap-datetimepicker.min" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container" style="width:1000px;">
          <div class="nav-collapse">
            <% if admin_signed_in? %>
              <ul class="nav pull-left">
                <li><%= link_to "Home", admin_dashboards_path %></li>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Drives", drives_path %></li>
                <li><%= link_to "Campaigns", campaigns_path %></li>
                <li><%= link_to "Products",products_path %></li>
              </ul>
              <ul class="nav pull-right">
                <li>
                  <%= link_to "Logout", destroy_admin_session_path, :method => "DELETE" %>
                </li>
              </ul>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <br/>
    <br/>
    <br/>

    <div class="container" style="padding-bottom:50px;width:1000px;">
      <% if notice %>
        <div class="alert alert-info" style="margin-top: 0px;">
          <a class="close" data-dismiss="alert">×</a>
          <strong><%= notice %></strong>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">×</a>
          <strong><%= alert %></strong>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amp Your Good</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application","bootstrap-datetimepicker.min", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse">
            <% if user_signed_in? %>
            <ul class="nav pull-right">
              <li><%= link_to "Logout", destroy_user_session_path, :method => "delete" %></li>
            </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br/>
    <br/>
    <br/>
    <div class="container" style="padding-bottom:50px;width:1000px;">
    <% if notice %>
      <div class="alert alert-info">
        <a class="close" data-dismiss="alert">×</a>
        <strong><%= notice %></strong>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>
        <strong><%= alert %></strong>
      </div>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>